#https://github.com/Animosity/CraftIRC/wiki/Complete-idiot's-introduction-to-yaml
#Docker-compose for financielemodule
version: '3.7'

secrets:
  konga_user_seed:
    file: ./userdb.data
  kong_node_seed:
    file: ./kong_node.data
    
services:
  kong:
    image: kong:2.8.0-alpine
    volumes:
      -  '.:/kong/declarative/'
    
    environment: 
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_DATABASE=off
      #- KONG_PG_HOST=host.docker.internal
      #- KONG_PG_USER=kong
      #- KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:9001, 0.0.0.0:9444 ssl
    networks:
      - kong-net
        
    ports:
        - 7000:8000
        - 7443:8443
        - 9001:9001
        - 9000:9000
        - 9443:9443
    
  konga:
    image: pantsel/konga
    networks: 
      - kong-net
    ports:
    - 1338:1338
    - 1337:1337
    secrets:
     - konga_user_seed
     - kong_node_seed
    environment:
      - NODE_ENV=development
      - TOKEN_SECRET=Roxit#123
      - PORT=1337
      - NO_AUTH=false
      - KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE=/run/secrets/kong_node_seed
      - KONGA_SEED_USER_DATA_SOURCE_FILE=/run/secrets/konga_user_seed
    depends_on:
      - kong
  testapis:
    build: 
     dockerfile: TestApis/Dockerfile
     context: ./Apis/TestApis
    environment:
      - ASPNETCORE_ENVIRONMENT=development

    ports:
      - 1400:80
      - 1401:443
    networks: 
      - kong-net
    depends_on:
      - kong
        
   
networks:
  kong-net: